### ISSUE TITLE
handler name is also the route name problem

### ISSUE THREAD

**Issue by mavbozo** [frankiesardo/tripod#1]
I tried using it in a very small cljs app and encounter error on uniqueness of route names.

My use case is 1 handler used by multiple slightly different pages for SEO A/B testing.

``` clojure
(defroutes routes
  [["/" home]
   ["/info" info-page]
   ["/info-2" info-page]
   ["/info-3" info-page]
   ["/info-4" info-page]])
```

By looking at your code, I see that the name of the route is also the name of the handler. It would be nice to come up with a way to name each route uniquely even though they use same handler.

**Comment by frankiesardo** [comment]
Hi @mavbozo 

Unique handler names for routes is a restriction introduced by pedestal so you can easily call `(path-for info-page)` and get the correct unique url for it.

Differently than pedestal tripod does not evaluate handlers. They are just data structures. So in your case I would do something like:

``` clj
(defhandler info-page [req] {..})

(defn make-info-page [n] (assoc info-page :name n)

(defroutes routes
 [["/" home]
   ["/info" (make-info-page :a)]
   ["/info-2" (make-info-page :b)]
   ["/info-3" (make-info-page :c)]
   ["/info-4" (make-info-page :d)]])
```

Ultimately `defhandler foo` expands to `{:name :foo :enter ...}` so you can create and manipulate them however you like.

Does this work for you?

**Comment by mavbozo** [comment]
happy new year @frankiesardo !

Yes! your solution works. 

Thank you.
