### ISSUE TITLE
core async support?

### ISSUE THREAD

**Issue by markaddleman** [frankiesardo/tripod#5]
Hi - 

I took a stab at adding core.async support to your interceptor library at https://github.com/frankiesardo/tripod/compare/master...markaddleman:master  

It was awfully easy given the headstart you already have in tripod - makes me think I'm missing something!  Would you provide some feedback?  I'd be happy to polish the code and provide proper pull request but I want to make sure I'm heading in the right direction.

**Comment by frankiesardo** [comment]
Hi @markaddleman 
Thanks for your contribution. Yes, adding async support should be trivial, I just never had the need for fully supporting it so it remained as a todo. This seems absolutely the right direction, if you're willing to test and make sure the async behaviour is working I'm happy to merge a PR in 👍  .
